### ISSUE TITLE
GitHub Campus Advisors Interview

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-muhammetfatihdogan#11]
Hi Muhammet Fatih,

GitHub Education would like to schedule a 1 on 1 interview with you regarding your Campus Advisor Application for Certification!

This meeting will be conducted via Zoom. We recommend that you download Zoom 15 minutes before your meeting [here](https://zoom.us/download). 

Please click [here](https://calendly.com/arelia/campus-advisor-interview) to schedule your Campus Advisor Interview.

We look forward to speaking with you.

Cheers,
@arelia
Developer Program Manager, Teachers
The GitHub Education Team

**Comment by muhammetfatihdogan** [comment]
Hi Arelia, I scheduled a meeting for September, 22 at 21.45
See you soon.

Best
Muhammet Fatih Doğan
Yıldız Technical University
